# Generated by Django 3.2.6 on 2021-08-07 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=200)),
                ('name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=11)),
                ('birth', models.CharField(max_length=9)),
                ('location', models.CharField(max_length=200)),
                ('cabinet', models.CharField(choices=[('인하대역', '인하대역'), ('신촌역', '신촌역'), ('회기역', '회기역')], max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자'), ('선택안함', '선택안함')], max_length=5)),
                ('marketing', models.BooleanField()),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
