# Generated by Django 3.2.6 on 2021-08-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish_item',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.timestampmodel')),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish.wish_list')),
            ],
            options={
                'db_table': 'WishItem',
            },
            bases=('goods.timestampmodel',),
        ),
    ]
