# Generated by Django 3.2.6 on 2021-08-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_wish_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish_item',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
    ]
