# Generated by Django 3.2.6 on 2021-08-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.timestampmodel')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=50)),
                ('type', models.CharField(choices=[('냉장', '냉장상품'), ('냉동', '냉동식품'), ('그외', '그 외 모두')], max_length=5)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('recruitment_no', models.IntegerField(max_length=10)),
                ('expired', models.CharField(max_length=8)),
                ('pre_people', models.IntegerField(max_length=10)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            bases=('goods.timestampmodel',),
        ),
    ]
