# Generated by Django 3.2.6 on 2021-08-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pre_people',
            field=models.IntegerField(default=0),
        ),
    ]
