# Generated by Django 3.2.6 on 2021-08-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_comments',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.timestampmodel')),
                ('content', models.TextField()),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_comment', to='goods.goods', verbose_name='댓글')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            bases=('goods.timestampmodel',),
        ),
    ]
