# Generated by Django 3.2.6 on 2021-08-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.timestampmodel')),
                ('pay_time', models.CharField(max_length=20)),
                ('goods_update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='결제제품')),
            ],
            bases=('goods.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.CharField(max_length=8)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet_manage', verbose_name='배송위치')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.payment', verbose_name='주문번호')),
            ],
        ),
    ]
