# Generated by Django 3.2.6 on 2021-08-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.timestampmodel')),
                ('quantity', models.IntegerField(verbose_name='주문수량')),
                ('goods_update_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='결제제품')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='주문자')),
            ],
            bases=('goods.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Barcoad',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.timestampmodel')),
                ('order_barcode', models.ImageField(upload_to='')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            bases=('goods.timestampmodel',),
        ),
    ]
