# Generated by Django 3.2.6 on 2021-08-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='주문수량'),
        ),
    ]
