# Generated by Django 3.2.6 on 2021-08-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('location_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_id', models.IntegerField()),
                ('in_use', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet_manage', verbose_name='각각캐비넷')),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_id', models.IntegerField()),
                ('in_use', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet_manage', verbose_name='각각캐비넷')),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_id', models.IntegerField()),
                ('in_use', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet_manage', verbose_name='각각캐비넷')),
            ],
        ),
    ]
