# Generated by Django 3.2.6 on 2021-08-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet_1',
            name='can_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabinet_1',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabinet_2',
            name='can_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabinet_2',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabinet_3',
            name='can_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabinet_3',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
