# Generated by Django 3.2.6 on 2021-08-07 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('norm_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('냉장', '냉장상품'), ('냉동', '냉동식품'), ('그외', '그 외 모두')], max_length=5)),
                ('tags', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('recruitment_no', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('expired', models.CharField(max_length=8)),
                ('pre_people', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deadline', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='goods/%Y/%m/%d')),
                ('url', models.URLField(blank=True, null=True)),
                ('available_display', models.BooleanField(default=True, verbose_name='Display')),
                ('available_order', models.BooleanField(default=True, verbose_name='Order')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='goods.category')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='작성자')),
            ],
            options={
                'ordering': ['-modified', '-created'],
            },
        ),
    ]
