# Generated by Django 3.2.6 on 2021-08-10 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pre_people',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
