# Generated by Django 3.2.6 on 2021-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='dydrkfsla0821@gmail.com', max_length=200)),
                ('name', models.CharField(default='', max_length=10)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('ph_no', models.CharField(default='', max_length=11)),
                ('birth', models.CharField(default='', max_length=9)),
                ('location', models.CharField(default='', max_length=100)),
                ('cabinet', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, default='../static/img/default_img.jpg', null=True, upload_to='user')),
            ],
        ),
    ]
