# Generated by Django 3.2.6 on 2021-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('ph_no', models.CharField(max_length=11)),
                ('birth', models.CharField(max_length=9)),
                ('location', models.CharField(max_length=100)),
                ('cabinet', models.CharField(max_length=100)),
            ],
        ),
    ]
