# Generated by Django 3.2.6 on 2021-08-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cabinet',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
