# Generated by Django 3.2.6 on 2021-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='dydrkfsla0821@gmail.com', max_length=20),
        ),
    ]
