# Generated by Django 3.2.6 on 2021-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210812_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../static/img/default_img.jpg', null=True, upload_to='user'),
        ),
    ]
