# Generated by Django 3.2.6 on 2021-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210812_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cabinet',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
